### ISSUE TITLE
Error installing on Windows: undefined syscall.Stat_t

### ISSUE THREAD

**Issue by osklyar** [src-d/go-git#271]
For the following two versions of Go 1.7.5 and 1.8rc3 windows/amd64 I am observing the following error when installing the library. This error does not occur on Linux (only tested with 1.8rc3).

    $ go get -u srcd.works/go-git.v4/...
    # srcd.works/go-git.v4
    ..\..\..\srcd.works\go-git.v4\worktree.go:74: undefined: syscall.Stat_t
    ..\..\..\srcd.works\go-git.v4\worktree.go:92: undefined: syscall.Stat_t

In case it matters, `go` was executed using `Git Bash`

**Comment by osklyar** [comment]
The issue has already been fixed in the current master, which also permits cross-compiling to Windows on Linux.

**Comment by ewilazarus** [comment]
I'm still getting this error on Windows.
Currently using git bash and go1.8 windows/amd64

**Comment by osklyar** [comment]
`srcd.works\go-git.v4` is actually behind master so try cloning master into `srcd.works\go-git.v4` instead of `github.com/src-d/go-git` or configure an override in your package manager to checkout the latter for the former (for me worked with `dep`).
